force-app/main/default/objects/pedidoDigitado__c/pedidoDigitado__c.object-meta.xml
<CustomObject>
    <description>Objeto para acompanhamento de pedido digitados.</description>
    <label>Pedido Digitado</label>
    <nameField>
        <label>Pedido Marketplace</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pedidos Digitados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/pedidoDigitado__c/fields/pedidoDigitado__c.field-meta.xml
<CustomField>
    <fullName>pedidoDigitado__c</fullName>
    <description>Pedido digitado no ábacos.</description>
    <label>Pedido digitado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/pedidoDigitado__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description>Status do pedido.</description>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MonitoraStatusTest.cls
@isTest
public with sharing class MonitoraStatusTest { 
   
   static testMethod void deveriaRetornarPedidoAtualizado(){

      StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
      mock.setStaticResource('respPedido');
      mock.setStatusCode(200);
      mock.setHeader('Content-Type', 'application/json');
      Test.setMock(HttpCalloutMock.class, mock);

      pedidoDigitado__c pedido = new pedidoDigitado__c();
      pedido.Name = '14614144';
      insert pedido;

      List<pedidoDigitado__c> listaPedidos = [select Id, Name, status__c
                                              from pedidoDigitado__c];

      System.assertEquals(1, listaPedidos.size());
      System.assertEquals(null, listaPedidos[0].status__c);

      Test.startTest();
      Database.executeBatch(new MonitoraStatus());
      Test.stopTest();

      listaPedidos = [select Id, Name, status__c
                      from pedidoDigitado__c];

      System.assertEquals('FATURADO', listaPedidos[0].status__c);

     }
}